# Generated by Django 5.0.1 on 2024-01-27 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0002_rename_course_id_favorite_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='course',
            new_name='course_id',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='course',
            new_name='course_id',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='user_id',
        ),
    ]
