# Generated by Django 5.0.1 on 2024-01-27 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0003_rename_course_favorite_course_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user_id',
            new_name='user',
        ),
    ]
