# Generated by Django 5.0.1 on 2024-01-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0005_alter_course_final_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='link',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='text_review',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='patronymic',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='final_rating',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
