# Generated by Django 5.0.1 on 2024-01-31 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0006_course_link_course_price_review_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='pub_date',
            field=models.DateTimeField(null=True),
        ),
    ]
