# Generated by Django 5.0.1 on 2024-02-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0010_alter_course_training_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=150),
        ),
    ]
