# Generated by Django 5.0.1 on 2024-02-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0010_alter_course_training_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='final_rating',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True, verbose_name='Рейтинг курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='link',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='course',
            name='training_period',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True, verbose_name='Рейтинг человека'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text_review',
            field=models.TextField(default=''),
        ),
    ]
