# Generated by Django 5.0.1 on 2024-02-19 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0011_alter_course_course_name'),
        ('aggregator', '0012_alter_course_final_rating_alter_course_link_and_more'),
    ]

    operations = [
    ]
