# Generated by Django 5.0.1 on 2024-02-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0013_merge_20240219_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='final_rating',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True, verbose_name='Рейтинг курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='link',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='training_period',
            field=models.IntegerField(default=0),
        ),
    ]
