# Generated by Django 5.0.1 on 2024-02-20 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0015_alter_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='owner_img',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
    ]
