# Generated by Django 5.0.1 on 2024-02-20 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0017_alter_course_owner_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='owner_img',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
    ]
