# Generated by Django 5.0.1 on 2024-03-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0022_alter_favorite_user_alter_review_user_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='course',
        ),
        migrations.AddField(
            model_name='favorite',
            name='course',
            field=models.ManyToManyField(to='aggregator.course'),
        ),
    ]
