# Generated by Django 5.0.1 on 2024-06-09 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0025_сomparison'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
    ]
